### ISSUE TITLE
Probably Just Being Stupid, But:

### ISSUE THREAD

**Issue by Skerminkel** [kiooeht/StSLib#4]
Hi, I recently downloaded ModTheSpire and have not been able to get it to work. I tried all the trouble shooting, and made sure that the mods I am trying to run have all been updated AFTER BaseMod was last updated. 

I'm updating Slay The Spire as we speak (slow internet)  and as if that fixes it I will close the issue. But it looks like the issues might be with StSLib (which is why I'm posting it here, idk, my coding knowledge is severely limited), here is the error:

Running with debug mode turned ON...

ModVersion Info:
 - Java version (1.8.0_144)
 - Slay the Spire (11-15-2018)
 - ModTheSpire (3.6.3)
Mod list:
 - basemod (5.5.0)
 - stslib (1.10.0)
 - Friendly_Minions_0987678 (0.1.1)

Begin patching...
Finding core patches...
Finding patches...
com.evacipated.cardcrawl.modthespire.patcher.PatchingException: com.megacrit.cardcrawl.screens.SingleCardViewPopup.renderPortrait(com.badlogic.gdx.graphics.g2d.SpriteBatch): Location matching given description could not be found for patch
	at com.evacipated.cardcrawl.modthespire.lib.LineFinder.findInOrder(LineFinder.java:39)
	at com.evacipated.cardcrawl.modthespire.lib.LineFinder.findInOrder(LineFinder.java:32)
	at basemod.patches.com.megacrit.cardcrawl.screens.SingleCardViewPopup.MissingPortraitFix$Locator.Locate(MissingPortraitFix.java:34)
	at com.evacipated.cardcrawl.modthespire.patcher.LocatorInfo.findLines(LocatorInfo.java:22)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:310)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:185)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:199)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:266)
	at java.lang.Thread.run(Unknown Source)

I hope I don't seem overly dumb, but I probably do, haha.

**Comment by Skerminkel** [comment]
Updating fixed the issue, thanks!
